### ISSUE TITLE
Playlists failing to download

### ISSUE THREAD

**Issue by starcrash-13** [pranjalagg/spdl#15]
Playlists are failing to download, and throwing KeyError: 'cover'
<img width="725" alt="Screenshot 2024-09-26 230145" src="https://github.com/user-attachments/assets/37df7562-c969-410f-9ca0-d44977c39d32">

**Comment by scythe000** [comment]
Same here on windows

**Comment by scythe000** [comment]
I fixed it. It's because we don't always get a cover back:

def make_unique_song_objects(track_list, trackname_convention):
    song_list = []
    for track in track_list:
        song_list.append(
            Song(
                title=re.sub(NAME_SANITIZE_REGEX, "_", track['title']),
                artists=re.sub(NAME_SANITIZE_REGEX, "_", track['artists']),
                album=track.get('album', 'Unknown Album'),
                cover=track.get('cover', 'default_cover.jpg'),  # Use a default value for missing covers
                link=f"https://open.spotify.com/track/{track['id']}"
            )
        )
    unique_songs, duplicate_songs = dict_unique(song_list, trackname_convention)

    if (len(duplicate_songs)):
        print("\tDuplicate songs: ", len(duplicate_songs))
        for index, song_name in enumerate(duplicate_songs, 1):
            print(f"\t\t{index}: {song_name}")

    print("\n\tUnique Songs in playlist: ", len(unique_songs))
    for index, song_name in enumerate(unique_songs.keys(), 1):
        print(f"\t\t{index}: {song_name}")
    
    return unique_songs

**Comment by scythe000** [comment]
also update:
`def download_playlist_tracks(playlist_link, outpath, create_folder, trackname_convention, max_attempts=3):
    print("\nPlaylist link identified")
    song_list_dict, playlist_name_old = get_playlist_info(playlist_link, trackname_convention)
    playlist_name = re.sub(NAME_SANITIZE_REGEX, "_", playlist_name_old)
    if (playlist_name != playlist_name_old):
        print(f'\n"{playlist_name_old}" is not a valid folder name. Using "{playlist_name}" instead.')

    if create_folder:
        outpath = os.path.join(outpath, playlist_name)

    if os.path.exists(outpath):
        song_list_dict = check_existing_tracks(song_list_dict, outpath)
    if not song_list_dict:
        print(f"\nAll tracks from {playlist_name} already exist in the directory ({outpath}).")
        return

    print(f"\nDownloading {len(song_list_dict)} new track(s) from {playlist_name} to ({outpath})")
    print("-" * 40)
    for index, trackname in enumerate(song_list_dict.keys(), 1):
        print(f"{index}/{len(song_list_dict)}: {trackname}")
        for attempt in range(max_attempts):
            try:
                resp = get_track_info(song_list_dict[trackname].link)
                resolve_path(outpath, playlist_folder=True)
                save_status = save_audio(trackname, resp['link'], outpath)
                if save_status:
                    cover_url = song_list_dict[trackname].cover
                    if cover_url.startswith('http'):  # Only try to download if it's a valid URL
                        cover_art = requests.get(cover_url).content
                        attach_cover_art(trackname, cover_art, outpath)
                    else:
                        print(f"Skipping cover art for {trackname} (No valid cover URL)")
                    break
            except Exception as e:
                logging.error(f"Attempt {attempt+1} - {playlist_name}: {trackname} --> {e}")
                print(f"\t\tAttempt {attempt+1} failed with error: ", e)

    remove_empty_files(outpath)
`

**Comment by starcrash-13** [comment]
Thanks for looking into it! Python is not a language that I know, and I'm having trouble integrating this code, could you possibly post the whole script with changes included? Thanks!

Edit: I managed to get it working, do we have any idea why it's not able to pull the cover image?

**Comment by lucasroyerdev** [comment]
Hi,

I went through the code because I really wanted to get a reliable playlist download solution. I was surprised that unique tracks worked but not playlist.

I discovered that the playlist way doesn't reuse the unique track download way which was odd to me because this one works.

I also reorganize the code to help me to understand it. I created a fork with functional playlist downloading with cover : https://github.com/aliocha44/spdl/tree/playlist-download

I also implemented my suggestion ([Issue 17](https://github.com/pranjalagg/spdl/issues/17))

Feel free to try it and give your return, I did it quickly, but I hope to have more time to continue.

**Comment by starcrash-13** [comment]
Seems to work great, but it will not create the destination folder, and will error if the folder does not exist.

**Comment by aliocha44** [comment]
Ok, I check it.

**Comment by lucasroyerdev** [comment]
Hi, it's solved.

Small mistake coming from the change of using download_track function with both single tracks and playlist.

It should be better now : https://github.com/aliocha44/spdl/tree/playlist-download

**Comment by starcrash-13** [comment]
Awesome! I also get a PermissionError: Access is Denied whenever the script tries to run 'remove_empty_files', this was an issue in the original script too, do you have any info on why that might be happening? Thanks!

**Comment by lucasroyerdev** [comment]
Before any test or investigation, my first guess is that `os.remove` command needs that the python script is launched as administrator.

Just try to launch it with command prompt (cmd) as user, and it probably should solve the problem.

**Comment by starcrash-13** [comment]
It happens with regular and elevated cmd. It's not a big deal, as the download still happens, I just hate seeing errors, I'm also working on a GUI integration for the script, so I'm just looking for everything to run as smooth as possible. Thank you for your cover art fix!

**Comment by pranjalagg** [comment]
Hey everyone,

I’m glad to see that you’re using the project and finding bugs! I initially developed this as a side project and haven’t had much time to address edge cases.

I really appreciate your feedback. If you’re able to submit pull requests for the fixes, I’d be happy to merge them so that everyone can benefit.

Thanks and cheers!

**Comment by lucasroyerdev** [comment]
@starcrash-13 

I just try on both WSL Ubuntu and Windows, with a previously empty file created by myself, and I didn't get any error message.

Can you precise which error message did you get ? 

Thanks
