### ISSUE TITLE
Unble to download playlist  KeyError: 'cover'

### ISSUE THREAD

**Issue by wagh-jayesh** [pranjalagg/spdl#16]
![git](https://github.com/user-attachments/assets/c967dc2c-8786-4f1a-a6b8-b5531e26495f)

OS Version - Windows 11

**Comment by starcrash-13** [comment]
This has been addressed here: [Issue 15](https://github.com/pranjalagg/spdl/issues/15).

The comments show a fix that bypasses the error, but there seems to be a wider issue because with the bypass in place it seems most playlists are now downloading without any cover art.

**Comment by lucasroyerdev** [comment]
Hi, I answer to [Issue 15](https://github.com/pranjalagg/spdl/issues/15.) with a working solution. Check it out :)

**Comment by wagh-jayesh** [comment]
@aliocha44 no still not working 
![image](https://github.com/user-attachments/assets/477b734a-f43b-4878-a305-190ac8d05106)
I think now the script is unable to create folder

**Comment by lucasroyerdev** [comment]
Hi, it's solved.

Small mistake coming from the change of using download_track function with both single tracks and playlist.

It should be better now : https://github.com/aliocha44/spdl/tree/playlist-download

**Comment by wagh-jayesh** [comment]
@aliocha44 but i gues another error occured 
![image](https://github.com/user-attachments/assets/ded1e4fb-58af-47cc-a671-accdb59a51d2)
may be regarding to some track name

**Comment by lucasroyerdev** [comment]
Before more investigation, did you try outside of a OneDrive folder ? I don't really know if they are recognized and if they work as proper folder. It seems to not be the case with Google Drive for example.

**Comment by wagh-jayesh** [comment]
@aliocha44 still not 
![image](https://github.com/user-attachments/assets/b20a6924-3add-474e-a086-616f1f1612ff)

**Comment by wagh-jayesh** [comment]
@aliocha44  not working for some specific playlist
ex :- https://open.spotify.com/playlist/1iHMuzGVigNepVmxk5Kh6Q

**Comment by lucasroyerdev** [comment]
It's works on my side : 

![image](https://github.com/user-attachments/assets/1bef8220-344e-4c10-a2ff-5b082db126f2)

For development, i'm running it on WSL Ubuntu. I try in Windows tomorrow.

**Comment by wagh-jayesh** [comment]
@aliocha44  Ive made another new plalist and then add old playlist to that and now it is working 
Thanks a loot

**Comment by lucasroyerdev** [comment]
Ok, it's weird but i'm glad it worked. 

Keep me in touch if you find new problems !

**Comment by pranjalagg** [comment]
The fix to this has now been pushed to the main branch. The issue should be resolved now.
I am closing this issue, feel free to reopen it if the issue persists.
